# Generated by Django 6.0.1 on 2026-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
