# Generated by Django 6.0.1 on 2026-01-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_department_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
