# Generated by Django 6.0.1 on 2026-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.ManyToManyField(related_name='absent_emp', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.ManyToManyField(related_name='present_emp', to='employee.employee'),
        ),
    ]
